-- Migration 004: Geographic Hierarchy (State -> District -> County -> Court)
-- Creates a strict jurisdiction hierarchy to replace free-text location fields
-- 
-- Hierarchy:
--   State (Washington)
--   └── Appellate District (Division I, II, III)
--       └── County (King, Pierce, etc.)
--           └── Court (King County Superior Court, etc.)

-- ============================================
-- STEP 1: Create the jurisdictions table
-- ============================================
-- Self-referencing hierarchy like issue_taxonomy
-- Level 0: State
-- Level 1: Appellate District (Division)
-- Level 2: County
-- Level 3: Court (optional, for specific court instances)

CREATE TABLE IF NOT EXISTS jurisdictions (
    jurisdiction_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_id BIGINT REFERENCES jurisdictions(jurisdiction_id) ON DELETE SET NULL,
    name CITEXT NOT NULL,
    jurisdiction_type CITEXT NOT NULL CHECK (jurisdiction_type IN ('state', 'district', 'county', 'court')),
    abbreviation CITEXT,  -- e.g., 'WA', 'DIV1', 'KING'
    fips_code VARCHAR(10),  -- Federal county codes if needed
    level INTEGER NOT NULL DEFAULT 0,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    
    UNIQUE(parent_id, name, jurisdiction_type)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_jurisdictions_parent ON jurisdictions(parent_id);
CREATE INDEX IF NOT EXISTS idx_jurisdictions_type ON jurisdictions(jurisdiction_type);
CREATE INDEX IF NOT EXISTS idx_jurisdictions_name ON jurisdictions(name);
CREATE INDEX IF NOT EXISTS idx_jurisdictions_level ON jurisdictions(level);

-- Trigger for updated_at
CREATE TRIGGER trg_jurisdictions_updated 
    BEFORE UPDATE ON jurisdictions 
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================
-- STEP 2: Insert Washington State (Level 0)
-- ============================================
INSERT INTO jurisdictions (name, jurisdiction_type, abbreviation, level, display_order)
VALUES ('Washington', 'state', 'WA', 0, 1)
ON CONFLICT DO NOTHING;

-- ============================================
-- STEP 3: Insert Appellate Districts (Level 1)
-- ============================================
DO $$
DECLARE
    wa_id BIGINT;
BEGIN
    SELECT jurisdiction_id INTO wa_id FROM jurisdictions WHERE jurisdiction_type = 'state' AND name = 'Washington';
    
    INSERT INTO jurisdictions (parent_id, name, jurisdiction_type, abbreviation, level, display_order)
    VALUES 
        (wa_id, 'Division I', 'district', 'DIV1', 1, 1),
        (wa_id, 'Division II', 'district', 'DIV2', 1, 2),
        (wa_id, 'Division III', 'district', 'DIV3', 1, 3)
    ON CONFLICT DO NOTHING;
END $$;

-- ============================================
-- STEP 4: Insert all 39 Washington Counties (Level 2)
-- ============================================
-- Washington has 39 counties. We'll assign them to their appellate divisions.
-- Division I: King, Snohomish, Whatcom, Skagit, Island, San Juan
-- Division II: Pierce, Thurston, Clark, Cowlitz, Lewis, Mason, etc.
-- Division III: Spokane, Yakima, Benton, Franklin, Grant, etc.

DO $$
DECLARE
    div1_id BIGINT;
    div2_id BIGINT;
    div3_id BIGINT;
BEGIN
    SELECT jurisdiction_id INTO div1_id FROM jurisdictions WHERE name = 'Division I' AND jurisdiction_type = 'district';
    SELECT jurisdiction_id INTO div2_id FROM jurisdictions WHERE name = 'Division II' AND jurisdiction_type = 'district';
    SELECT jurisdiction_id INTO div3_id FROM jurisdictions WHERE name = 'Division III' AND jurisdiction_type = 'district';
    
    -- Division I Counties (Western WA - Seattle area)
    INSERT INTO jurisdictions (parent_id, name, jurisdiction_type, abbreviation, level, display_order)
    VALUES 
        (div1_id, 'King', 'county', 'KING', 2, 1),
        (div1_id, 'Snohomish', 'county', 'SNOH', 2, 2),
        (div1_id, 'Whatcom', 'county', 'WHAT', 2, 3),
        (div1_id, 'Skagit', 'county', 'SKAG', 2, 4),
        (div1_id, 'Island', 'county', 'ISLA', 2, 5),
        (div1_id, 'San Juan', 'county', 'SANJ', 2, 6)
    ON CONFLICT DO NOTHING;
    
    -- Division II Counties (SW & Central WA - Tacoma area)
    INSERT INTO jurisdictions (parent_id, name, jurisdiction_type, abbreviation, level, display_order)
    VALUES 
        (div2_id, 'Pierce', 'county', 'PIER', 2, 1),
        (div2_id, 'Thurston', 'county', 'THUR', 2, 2),
        (div2_id, 'Clark', 'county', 'CLAR', 2, 3),
        (div2_id, 'Cowlitz', 'county', 'COWL', 2, 4),
        (div2_id, 'Lewis', 'county', 'LEWI', 2, 5),
        (div2_id, 'Mason', 'county', 'MASO', 2, 6),
        (div2_id, 'Grays Harbor', 'county', 'GRAY', 2, 7),
        (div2_id, 'Pacific', 'county', 'PACI', 2, 8),
        (div2_id, 'Wahkiakum', 'county', 'WAHK', 2, 9),
        (div2_id, 'Kitsap', 'county', 'KITS', 2, 10),
        (div2_id, 'Clallam', 'county', 'CLAL', 2, 11),
        (div2_id, 'Jefferson', 'county', 'JEFF', 2, 12),
        (div2_id, 'Skamania', 'county', 'SKAM', 2, 13)
    ON CONFLICT DO NOTHING;
    
    -- Division III Counties (Eastern WA - Spokane area)
    INSERT INTO jurisdictions (parent_id, name, jurisdiction_type, abbreviation, level, display_order)
    VALUES 
        (div3_id, 'Spokane', 'county', 'SPOK', 2, 1),
        (div3_id, 'Yakima', 'county', 'YAKI', 2, 2),
        (div3_id, 'Benton', 'county', 'BENT', 2, 3),
        (div3_id, 'Franklin', 'county', 'FRAN', 2, 4),
        (div3_id, 'Grant', 'county', 'GRAN', 2, 5),
        (div3_id, 'Chelan', 'county', 'CHEL', 2, 6),
        (div3_id, 'Kittitas', 'county', 'KITT', 2, 7),
        (div3_id, 'Klickitat', 'county', 'KLIC', 2, 8),
        (div3_id, 'Okanogan', 'county', 'OKAN', 2, 9),
        (div3_id, 'Douglas', 'county', 'DOUG', 2, 10),
        (div3_id, 'Adams', 'county', 'ADAM', 2, 11),
        (div3_id, 'Asotin', 'county', 'ASOT', 2, 12),
        (div3_id, 'Columbia', 'county', 'COLU', 2, 13),
        (div3_id, 'Ferry', 'county', 'FERR', 2, 14),
        (div3_id, 'Garfield', 'county', 'GARF', 2, 15),
        (div3_id, 'Lincoln', 'county', 'LINC', 2, 16),
        (div3_id, 'Pend Oreille', 'county', 'PEND', 2, 17),
        (div3_id, 'Stevens', 'county', 'STEV', 2, 18),
        (div3_id, 'Walla Walla', 'county', 'WALL', 2, 19),
        (div3_id, 'Whitman', 'county', 'WHIT', 2, 20)
    ON CONFLICT DO NOTHING;
END $$;

-- ============================================
-- STEP 5: Create county name normalization function
-- ============================================
-- This helps map messy text like "King County" or "king" to proper county name
CREATE OR REPLACE FUNCTION normalize_county_name(raw_county TEXT)
RETURNS CITEXT AS $$
BEGIN
    IF raw_county IS NULL OR raw_county = '' OR raw_county = 'Unknown' THEN
        RETURN NULL;
    END IF;
    
    -- Remove " County" suffix and trim
    RETURN TRIM(REGEXP_REPLACE(raw_county, '\s*County\s*$', '', 'i'))::CITEXT;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ============================================
-- STEP 6: Add jurisdiction_id to cases table
-- ============================================
-- Link to county level (we can traverse up to district/state)
ALTER TABLE cases 
ADD COLUMN IF NOT EXISTS jurisdiction_id BIGINT REFERENCES jurisdictions(jurisdiction_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_cases_jurisdiction ON cases(jurisdiction_id);

-- ============================================
-- STEP 7: Populate jurisdiction_id based on existing county text
-- ============================================
UPDATE cases c
SET jurisdiction_id = j.jurisdiction_id
FROM jurisdictions j
WHERE j.jurisdiction_type = 'county'
  AND j.name = normalize_county_name(c.county)
  AND c.jurisdiction_id IS NULL;

-- ============================================
-- STEP 8: Verify migration
-- ============================================
-- Check hierarchy:
-- SELECT j.*, p.name as parent_name FROM jurisdictions j LEFT JOIN jurisdictions p ON j.parent_id = p.jurisdiction_id ORDER BY j.level, j.parent_id, j.display_order;

-- Check case linkage:
-- SELECT COUNT(*) as total, COUNT(jurisdiction_id) as linked FROM cases;

-- Example query - get all cases from Division I:
-- SELECT c.case_id, c.title, j.name as county, d.name as district
-- FROM cases c
-- JOIN jurisdictions j ON c.jurisdiction_id = j.jurisdiction_id
-- JOIN jurisdictions d ON j.parent_id = d.jurisdiction_id
-- WHERE d.name = 'Division I';
